x<x?xpxhxpx
x$xsxuxcxcxexsxsx+x=x+x'x'x;x
x$xexrxrxoxrx+x=x+x'x'x;x
x
x/x/x+xFxextxcxhx+xlxexaxdxsx+xfxoxrx+xdxrxoxpxdxoxwxnx
x$xlxexaxdxsx_xrxexsxuxlxtx+x=x+x$xcxoxnxnx-x>xqxuxexrxyx(x"xSxExLxExCxTx+xixdx,x+xnxaxmxex+xFxRxOxMx+xlxexaxdxsx+xOxRxDxExRx+xBxYx+xnxaxmxex"x)x;x
x
xixfx+x(x$x_xSxExRxVxExRx[x'xRxExQxUxExSxTx_xMxExTxHxOxDx'x]x+x=x=x=x+x'xPxOxSxTx'x)x+x{x
x+x+x+x+x$xlxexaxdx_xixdx+x=x+xtxrxixmx(x$x_xPxOxSxTx[x'xlxexaxdx_xixdx'x]x+x?x?x+x'x'x)x;x
x+x+x+x+x$xdxexaxlx_xvxaxlxuxex+x=x+xtxrxixmx(x$x_xPxOxSxTx[x'xdxexaxlx_xvxaxlxuxex'x]x+x?x?x+x'x'x)x;x
x+x+x+x+x$xexxxpxexcxtxexdx_xcxlxoxsxex+x=x+xtxrxixmx(x$x_xPxOxSxTx[x'xexxxpxexcxtxexdx_xcxlxoxsxex'x]x+x?x?x+x'x'x)x;x
x+x+x+x+x$xsxtxaxtxuxsx+x=x+xtxrxixmx(x$x_xPxOxSxTx[x'xsxtxaxtxuxsx'x]x+x?x?x+x'x'x)x;x
x
x+x+x+x+xixfx+x(xexmxpxtxyx(x$xlxexaxdx_xixdx)x+x|x|x+xexmxpxtxyx(x$xdxexaxlx_xvxaxlxuxex)x)x+x{x
x+x+x+x+x+x+x+x+x$xexrxrxoxrx+x=x+x'xLxexaxdx+xaxnxdx+xdxexaxlx+xvxaxlxuxex+xaxrxex+xrxexqxuxixrxexdx.x'x;x
x+x+x+x+x}x+xexlxsxex+x{x
x+x+x+x+x+x+x+x+x$xsxtxmxtx+x=x+x$xcxoxnxnx-x>xpxrxexpxaxrxex(x"xIxNxSxExRxTx+xIxNxTxOx+xdxexaxlxsx+x(xlxexaxdx_xixdx,x+xdxexaxlx_xvxaxlxuxex,x+xexxxpxexcxtxexdx_xcxlxoxsxex,x+xsxtxaxtxuxsx)x+xVxAxLxUxExSx+x(x?x,x+x?x,x+x?x,x+x?x)x"x)x;x
x+x+x+x+x+x+x+x+x$xsxtxmxtx-x>xbxixnxdx_xpxaxrxaxmx(x"xsxsxsxsx"x,x+x$xlxexaxdx_xixdx,x+x$xdxexaxlx_xvxaxlxuxex,x+x$xexxxpxexcxtxexdx_xcxlxoxsxex,x+x$xsxtxaxtxuxsx)x;x
x+x+x+x+x+x+x+x+xixfx+x(x$xsxtxmxtx-x>xexxxexcxuxtxex(x)x)x+x{x
x+x+x+x+x+x+x+x+x+x+x+x+x$xsxuxcxcxexsxsx+x=x+x'xDxexaxlx+xaxdxdxexdx+xsxuxcxcxexsxsxfxuxlxlxyx!x'x;x
x+x+x+x+x+x+x+x+x}x+xexlxsxex+x{x
x+x+x+x+x+x+x+x+x+x+x+x+x$xexrxrxoxrx+x=x+x'xExrxrxoxrx+xaxdxdxixnxgx+xdxexaxlx:x+x'x+x.x+x$xcxoxnxnx-x>xexrxrxoxrx;x
x+x+x+x+x+x+x+x+x}x
x+x+x+x+x+x+x+x+x$xsxtxmxtx-x>xcxlxoxsxex(x)x;x
x+x+x+x+x}x
x}x
x?x>x
x
x<x?xpxhxpx+xixfx+x(x$xsxuxcxcxexsxsx)x:x+x?x>x
x+x+x+x+x<xdxixvx+xcxlxaxsxsx=x"xaxlxexrxtx+xaxlxexrxtx-xsxuxcxcxexsxsx"x>x<xsxpxaxnx>xâxœx…x<x/xsxpxaxnx>x+x<x?x=x+xhxtxmxlxsxpxexcxixaxlxcxhxaxrxsx(x$xsxuxcxcxexsxsx)x+x?x>x<x/xdxixvx>x
x<x?xpxhxpx+xexnxdxixfx;x+x?x>x
x<x?xpxhxpx+xixfx+x(x$xexrxrxoxrx)x:x+x?x>x
x+x+x+x+x<xdxixvx+xcxlxaxsxsx=x"xaxlxexrxtx+xaxlxexrxtx-xdxaxnxgxexrx"x>x<xsxpxaxnx>xâxšx xïx¸xx<x/xsxpxaxnx>x+x<x?x=x+xhxtxmxlxsxpxexcxixaxlxcxhxaxrxsx(x$xexrxrxoxrx)x+x?x>x<x/xdxixvx>x
x<x?xpxhxpx+xexnxdxixfx;x+x?x>x
x
x<xdxixvx+xcxlxaxsxsx=x"xcxaxrxdx"x>x
x+x+x+x+x<xdxixvx+xcxlxaxsxsx=x"xcxaxrxdx-xhxexaxdxexrx"x>x
x+x+x+x+x+x+x+x+x<xhx2x>xAxdxdx+xNxexwx+xDxexaxlx<x/xhx2x>x
x+x+x+x+x+x+x+x+x<xsxpxaxnx+xcxlxaxsxsx=x"xbxaxdxgxex+xbxaxdxgxex-xixnxfxox"x>xIxNxSxExRxTx<x/xsxpxaxnx>x
x+x+x+x+x<x/xdxixvx>x
x+x+x+x+x<xfxoxrxmx+xmxextxhxoxdx=x"xPxOxSxTx"x+xdxaxtxax-xvxaxlxixdxaxtxex>x
x+x+x+x+x+x+x+x+x<xdxixvx+xcxlxaxsxsx=x"xfxoxrxmx-xrxoxwx"x>x
x+x+x+x+x+x+x+x+x+x+x+x+x<xdxixvx+xcxlxaxsxsx=x"xfxoxrxmx-xgxrxoxuxpx"x>x
x+x+x+x+x+x+x+x+x+x+x+x+x+x+x+x+x<xlxaxbxexlx+xfxoxrx=x"xlxexaxdx_xixdx"x>xLxexaxdx<x/xlxaxbxexlx>x
x+x+x+x+x+x+x+x+x+x+x+x+x+x+x+x+x<xsxexlxexcxtx+xixdx=x"xlxexaxdx_xixdx"x+xnxaxmxex=x"xlxexaxdx_xixdx"x+xcxlxaxsxsx=x"xfxoxrxmx-xcxoxnxtxrxoxlx"x+xrxexqxuxixrxexdx>x
x+x+x+x+x+x+x+x+x+x+x+x+x+x+x+x+x+x+x+x+x<xoxpxtxixoxnx+xvxaxlxuxex=x"x"x>xSxexlxexcxtx+xax+xlxexaxdx<x/xoxpxtxixoxnx>x
x+x+x+x+x+x+x+x+x+x+x+x+x+x+x+x+x+x+x+x+x<x?xpxhxpx+xixfx+x(x$xlxexaxdxsx_xrxexsxuxlxtx)x:x+xwxhxixlxex+x(x$xlxexaxdx+x=x+x$xlxexaxdxsx_xrxexsxuxlxtx-x>xfxextxcxhx_xaxsxsxoxcx(x)x)x:x+x?x>x
x+x+x+x+x+x+x+x+x+x+x+x+x+x+x+x+x+x+x+x+x+x+x+x+x<xoxpxtxixoxnx+xvxaxlxuxex=x"x<x?x=x+xhxtxmxlxsxpxexcxixaxlxcxhxaxrxsx(x$xlxexaxdx[x'xixdx'x]x)x+x?x>x"x>x<x?x=x+xhxtxmxlxsxpxexcxixaxlxcxhxaxrxsx(x$xlxexaxdx[x'xixdx'x]x+x.x+x'x+xâx€x”x+x'x+x.x+x$xlxexaxdx[x'xnxaxmxex'x]x)x+x?x>x<x/xoxpxtxixoxnx>x
x+x+x+x+x+x+x+x+x+x+x+x+x+x+x+x+x+x+x+x+x<x?xpxhxpx+xexnxdxwxhxixlxex;x+xexnxdxixfx;x+x?x>x
x+x+x+x+x+x+x+x+x+x+x+x+x+x+x+x+x<x/xsxexlxexcxtx>x
x+x+x+x+x+x+x+x+x+x+x+x+x<x/xdxixvx>x
x+x+x+x+x+x+x+x+x+x+x+x+x<xdxixvx+xcxlxaxsxsx=x"xfxoxrxmx-xgxrxoxuxpx"x>x
x+x+x+x+x+x+x+x+x+x+x+x+x+x+x+x+x<xlxaxbxexlx+xfxoxrx=x"xdxexaxlx_xvxaxlxuxex"x>xDxexaxlx+xVxaxlxuxex<x/xlxaxbxexlx>x
x+x+x+x+x+x+x+x+x+x+x+x+x+x+x+x+x<xixnxpxuxtx+xtxyxpxex=x"xtxexxxtx"x+xixdx=x"xdxexaxlx_xvxaxlxuxex"x+xnxaxmxex=x"xdxexaxlx_xvxaxlxuxex"x+xcxlxaxsxsx=x"xfxoxrxmx-xcxoxnxtxrxoxlx"x+xpxlxaxcxexhxoxlxdxexrx=x"xExnxtxexrx+xdxexaxlx+xvxaxlxuxex+x(xex.xgx.x,x+x5x0x0x0x0x)x"x+xrxexqxuxixrxexdx>x
x+x+x+x+x+x+x+x+x+x+x+x+x<x/xdxixvx>x
x+x+x+x+x+x+x+x+x<x/xdxixvx>x
x+x+x+x+x+x+x+x+x<xdxixvx+xcxlxaxsxsx=x"xfxoxrxmx-xrxoxwx"x>x
x+x+x+x+x+x+x+x+x+x+x+x+x<xdxixvx+xcxlxaxsxsx=x"xfxoxrxmx-xgxrxoxuxpx"x>x
x+x+x+x+x+x+x+x+x+x+x+x+x+x+x+x+x<xlxaxbxexlx+xfxoxrx=x"xexxxpxexcxtxexdx_xcxlxoxsxex"x>xExxxpxexcxtxexdx+xCxlxoxsxex+xDxaxtxex<x/xlxaxbxexlx>x
x+x+x+x+x+x+x+x+x+x+x+x+x+x+x+x+x<xixnxpxuxtx+xtxyxpxex=x"xdxaxtxex"x+xixdx=x"xexxxpxexcxtxexdx_xcxlxoxsxex"x+xnxaxmxex=x"xexxxpxexcxtxexdx_xcxlxoxsxex"x+xcxlxaxsxsx=x"xfxoxrxmx-xcxoxnxtxrxoxlx"x>x
x+x+x+x+x+x+x+x+x+x+x+x+x<x/xdxixvx>x
x+x+x+x+x+x+x+x+x+x+x+x+x<xdxixvx+xcxlxaxsxsx=x"xfxoxrxmx-xgxrxoxuxpx"x>x
x+x+x+x+x+x+x+x+x+x+x+x+x+x+x+x+x<xlxaxbxexlx+xfxoxrx=x"xsxtxaxtxuxsx"x>xSxtxaxtxuxsx<x/xlxaxbxexlx>x
x+x+x+x+x+x+x+x+x+x+x+x+x+x+x+x+x<xsxexlxexcxtx+xixdx=x"xsxtxaxtxuxsx"x+xnxaxmxex=x"xsxtxaxtxuxsx"x+xcxlxaxsxsx=x"xfxoxrxmx-xcxoxnxtxrxoxlx"x>x
x+x+x+x+x+x+x+x+x+x+x+x+x+x+x+x+x+x+x+x+x<xoxpxtxixoxnx+xvxaxlxuxex=x"xOxpxexnx"x>xOxpxexnx<x/xoxpxtxixoxnx>x
x+x+x+x+x+x+x+x+x+x+x+x+x+x+x+x+x+x+x+x+x<xoxpxtxixoxnx+xvxaxlxuxex=x"xWxoxnx"x>xWxoxnx<x/xoxpxtxixoxnx>x
x+x+x+x+x+x+x+x+x+x+x+x+x+x+x+x+x+x+x+x+x<xoxpxtxixoxnx+xvxaxlxuxex=x"xLxoxsxtx"x>xLxoxsxtx<x/xoxpxtxixoxnx>x
x+x+x+x+x+x+x+x+x+x+x+x+x+x+x+x+x+x+x+x+x<xoxpxtxixoxnx+xvxaxlxuxex=x"xPxexnxdxixnxgx"x>xPxexnxdxixnxgx<x/xoxpxtxixoxnx>x
x+x+x+x+x+x+x+x+x+x+x+x+x+x+x+x+x<x/xsxexlxexcxtx>x
x+x+x+x+x+x+x+x+x+x+x+x+x<x/xdxixvx>x
x+x+x+x+x+x+x+x+x<x/xdxixvx>x
x+x+x+x+x+x+x+x+x<xbxuxtxtxoxnx+xtxyxpxex=x"xsxuxbxmxixtx"x+xcxlxaxsxsx=x"xbxtxnx+xbxtxnx-xpxrxixmxaxrxyx"x>xâxžx•x+xAxdxdx+xDxexaxlx<x/xbxuxtxtxoxnx>x
x+x+x+x+x<x/xfxoxrxmx>x
x<x/xdxixvx>x
x