x<x?xpxhxpx
x$xsxuxcxcxexsxsx+x=x+x'x'x;x
x$xexrxrxoxrx+x=x+x'x'x;x
x
xixfx+x(x$x_xSxExRxVxExRx[x'xRxExQxUxExSxTx_xMxExTxHxOxDx'x]x+x=x=x=x+x'xPxOxSxTx'x)x+x{x
x+x+x+x+x$xuxsxexrxnxaxmxex+x=x+xtxrxixmx(x$x_xPxOxSxTx[x'xuxsxexrxnxaxmxex'x]x+x?x?x+x'x'x)x;x
x+x+x+x+x$xpxaxsxsxwxoxrxdx+x=x+xtxrxixmx(x$x_xPxOxSxTx[x'xpxaxsxsxwxoxrxdx'x]x+x?x?x+x'x'x)x;x
x
x+x+x+x+xixfx+x(xexmxpxtxyx(x$xuxsxexrxnxaxmxex)x+x|x|x+xexmxpxtxyx(x$xpxaxsxsxwxoxrxdx)x)x+x{x
x+x+x+x+x+x+x+x+x$xexrxrxoxrx+x=x+x'xAxlxlx+xfxixexlxdxsx+xaxrxex+xrxexqxuxixrxexdx.x'x;x
x+x+x+x+x}x+xexlxsxex+x{x
x+x+x+x+x+x+x+x+x$xsxtxmxtx+x=x+x$xcxoxnxnx-x>xpxrxexpxaxrxex(x"xIxNxSxExRxTx+xIxNxTxOx+xaxdxmxixnxsx+x(xuxsxexrxnxaxmxex,x+xpxaxsxsxwxoxrxdx)x+xVxAxLxUxExSx+x(x?x,x+x?x)x"x)x;x
x+x+x+x+x+x+x+x+x$xsxtxmxtx-x>xbxixnxdx_xpxaxrxaxmx(x"xsxsx"x,x+x$xuxsxexrxnxaxmxex,x+x$xpxaxsxsxwxoxrxdx)x;x
x+x+x+x+x+x+x+x+xixfx+x(x$xsxtxmxtx-x>xexxxexcxuxtxex(x)x)x+x{x
x+x+x+x+x+x+x+x+x+x+x+x+x$xsxuxcxcxexsxsx+x=x+x'xAxdxmxixnx+xaxdxdxexdx+xsxuxcxcxexsxsxfxuxlxlxyx!x'x;x
x+x+x+x+x+x+x+x+x}x+xexlxsxex+x{x
x+x+x+x+x+x+x+x+x+x+x+x+x$xexrxrxoxrx+x=x+x'xExrxrxoxrx+xaxdxdxixnxgx+xaxdxmxixnx:x+x'x+x.x+x$xcxoxnxnx-x>xexrxrxoxrx;x
x+x+x+x+x+x+x+x+x}x
x+x+x+x+x+x+x+x+x$xsxtxmxtx-x>xcxlxoxsxex(x)x;x
x+x+x+x+x}x
x}x
x?x>x
x
x<x?xpxhxpx+xixfx+x(x$xsxuxcxcxexsxsx)x:x+x?x>x
x+x+x+x+x<xdxixvx+xcxlxaxsxsx=x"xaxlxexrxtx+xaxlxexrxtx-xsxuxcxcxexsxsx"x>x<xsxpxaxnx>xâxœx…x<x/xsxpxaxnx>x+x<x?x=x+xhxtxmxlxsxpxexcxixaxlxcxhxaxrxsx(x$xsxuxcxcxexsxsx)x+x?x>x<x/xdxixvx>x
x<x?xpxhxpx+xexnxdxixfx;x+x?x>x
x<x?xpxhxpx+xixfx+x(x$xexrxrxoxrx)x:x+x?x>x
x+x+x+x+x<xdxixvx+xcxlxaxsxsx=x"xaxlxexrxtx+xaxlxexrxtx-xdxaxnxgxexrx"x>x<xsxpxaxnx>xâxšx xïx¸xx<x/xsxpxaxnx>x+x<x?x=x+xhxtxmxlxsxpxexcxixaxlxcxhxaxrxsx(x$xexrxrxoxrx)x+x?x>x<x/xdxixvx>x
x<x?xpxhxpx+xexnxdxixfx;x+x?x>x
x
x<xdxixvx+xcxlxaxsxsx=x"xcxaxrxdx"x>x
x+x+x+x+x<xdxixvx+xcxlxaxsxsx=x"xcxaxrxdx-xhxexaxdxexrx"x>x
x+x+x+x+x+x+x+x+x<xhx2x>xAxdxdx+xNxexwx+xAxdxmxixnx<x/xhx2x>x
x+x+x+x+x+x+x+x+x<xsxpxaxnx+xcxlxaxsxsx=x"xbxaxdxgxex+xbxaxdxgxex-xixnxfxox"x>xIxNxSxExRxTx<x/xsxpxaxnx>x
x+x+x+x+x<x/xdxixvx>x
x+x+x+x+x<xfxoxrxmx+xmxextxhxoxdx=x"xPxOxSxTx"x+xdxaxtxax-xvxaxlxixdxaxtxex>x
x+x+x+x+x+x+x+x+x<xdxixvx+xcxlxaxsxsx=x"xfxoxrxmx-xrxoxwx"x>x
x+x+x+x+x+x+x+x+x+x+x+x+x<xdxixvx+xcxlxaxsxsx=x"xfxoxrxmx-xgxrxoxuxpx"x>x
x+x+x+x+x+x+x+x+x+x+x+x+x+x+x+x+x<xlxaxbxexlx+xfxoxrx=x"xuxsxexrxnxaxmxex"x>xUxsxexrxnxaxmxex<x/xlxaxbxexlx>x
x+x+x+x+x+x+x+x+x+x+x+x+x+x+x+x+x<xixnxpxuxtx+xtxyxpxex=x"xtxexxxtx"x+xixdx=x"xuxsxexrxnxaxmxex"x+xnxaxmxex=x"xuxsxexrxnxaxmxex"x+xcxlxaxsxsx=x"xfxoxrxmx-xcxoxnxtxrxoxlx"x+xpxlxaxcxexhxoxlxdxexrx=x"xExnxtxexrx+xuxsxexrxnxaxmxex"x+xrxexqxuxixrxexdx>x
x+x+x+x+x+x+x+x+x+x+x+x+x<x/xdxixvx>x
x+x+x+x+x+x+x+x+x+x+x+x+x<xdxixvx+xcxlxaxsxsx=x"xfxoxrxmx-xgxrxoxuxpx"x>x
x+x+x+x+x+x+x+x+x+x+x+x+x+x+x+x+x<xlxaxbxexlx+xfxoxrx=x"xpxaxsxsxwxoxrxdx"x>xPxaxsxsxwxoxrxdx<x/xlxaxbxexlx>x
x+x+x+x+x+x+x+x+x+x+x+x+x+x+x+x+x<xixnxpxuxtx+xtxyxpxex=x"xpxaxsxsxwxoxrxdx"x+xixdx=x"xpxaxsxsxwxoxrxdx"x+xnxaxmxex=x"xpxaxsxsxwxoxrxdx"x+xcxlxaxsxsx=x"xfxoxrxmx-xcxoxnxtxrxoxlx"x+xpxlxaxcxexhxoxlxdxexrx=x"xExnxtxexrx+xpxaxsxsxwxoxrxdx"x+xrxexqxuxixrxexdx>x
x+x+x+x+x+x+x+x+x+x+x+x+x<x/xdxixvx>x
x+x+x+x+x+x+x+x+x<x/xdxixvx>x
x+x+x+x+x+x+x+x+x<xbxuxtxtxoxnx+xtxyxpxex=x"xsxuxbxmxixtx"x+xcxlxaxsxsx=x"xbxtxnx+xbxtxnx-xpxrxixmxaxrxyx"x>xâxžx•x+xAxdxdx+xAxdxmxixnx<x/xbxuxtxtxoxnx>x
x+x+x+x+x<x/xfxoxrxmx>x
x<x/xdxixvx>x
x