x<x?xpxhxpx
x$xsxuxcxcxexsxsx+x=x+x'x'x;x
x$xexrxrxoxrx+x=x+x'x'x;x
x
x$xixdx+x=x+xixnxtxvxaxlx(x$x_xGxExTx[x'xixdx'x]x+x?x?x+x0x)x;x
xixfx+x(x$xixdx+x<x=x+x0x)x+x{x
x+x+x+x+xexcxhxox+x'x<xdxixvx+xcxlxaxsxsx=x"xaxlxexrxtx+xaxlxexrxtx-xdxaxnxgxexrx"x>xIxnxvxaxlxixdx+xdxexaxlx+xIxDx.x<x/xdxixvx>x'x;x
x+x+x+x+xrxextxuxrxnx;x
x}x
x
x$xlxexaxdxsx_xrxexsxuxlxtx+x=x+x$xcxoxnxnx-x>xqxuxexrxyx(x"xSxExLxExCxTx+xixdx,x+xnxaxmxex+xFxRxOxMx+xlxexaxdxsx+xOxRxDxExRx+xBxYx+xnxaxmxex"x)x;x
x
x$xsxtxmxtx+x=x+x$xcxoxnxnx-x>xpxrxexpxaxrxex(x"xSxExLxExCxTx+x*x+xFxRxOxMx+xdxexaxlxsx+xWxHxExRxEx+xixdx+x=x+x?x"x)x;x
x$xsxtxmxtx-x>xbxixnxdx_xpxaxrxaxmx(x"xix"x,x+x$xixdx)x;x
x$xsxtxmxtx-x>xexxxexcxuxtxex(x)x;x
x$xdxexaxlx+x=x+x$xsxtxmxtx-x>xgxextx_xrxexsxuxlxtx(x)x-x>xfxextxcxhx_xaxsxsxoxcx(x)x;x
x$xsxtxmxtx-x>xcxlxoxsxex(x)x;x
x
xixfx+x(x!x$xdxexaxlx)x+x{x
x+x+x+x+xexcxhxox+x'x<xdxixvx+xcxlxaxsxsx=x"xaxlxexrxtx+xaxlxexrxtx-xdxaxnxgxexrx"x>xDxexaxlx+xnxoxtx+xfxoxuxnxdx.x<x/xdxixvx>x'x;x
x+x+x+x+xrxextxuxrxnx;x
x}x
x
xixfx+x(x$x_xSxExRxVxExRx[x'xRxExQxUxExSxTx_xMxExTxHxOxDx'x]x+x=x=x=x+x'xPxOxSxTx'x)x+x{x
x+x+x+x+x$xlxexaxdx_xixdx+x=x+xtxrxixmx(x$x_xPxOxSxTx[x'xlxexaxdx_xixdx'x]x+x?x?x+x'x'x)x;x
x+x+x+x+x$xdxexaxlx_xvxaxlxuxex+x=x+xtxrxixmx(x$x_xPxOxSxTx[x'xdxexaxlx_xvxaxlxuxex'x]x+x?x?x+x'x'x)x;x
x+x+x+x+x$xexxxpxexcxtxexdx_xcxlxoxsxex+x=x+xtxrxixmx(x$x_xPxOxSxTx[x'xexxxpxexcxtxexdx_xcxlxoxsxex'x]x+x?x?x+x'x'x)x;x
x+x+x+x+x$xsxtxaxtxuxsx+x=x+xtxrxixmx(x$x_xPxOxSxTx[x'xsxtxaxtxuxsx'x]x+x?x?x+x'x'x)x;x
x
x+x+x+x+x$xsxtxmxtx+x=x+x$xcxoxnxnx-x>xpxrxexpxaxrxex(x"xUxPxDxAxTxEx+xdxexaxlxsx+xSxExTx+xlxexaxdx_xixdx=x?x,x+xdxexaxlx_xvxaxlxuxex=x?x,x+xexxxpxexcxtxexdx_xcxlxoxsxex=x?x,x+xsxtxaxtxuxsx=x?x+xWxHxExRxEx+xixdx=x?x"x)x;x
x+x+x+x+x$xsxtxmxtx-x>xbxixnxdx_xpxaxrxaxmx(x"xsxsxsxsxix"x,x+x$xlxexaxdx_xixdx,x+x$xdxexaxlx_xvxaxlxuxex,x+x$xexxxpxexcxtxexdx_xcxlxoxsxex,x+x$xsxtxaxtxuxsx,x+x$xixdx)x;x
x+x+x+x+xixfx+x(x$xsxtxmxtx-x>xexxxexcxuxtxex(x)x)x+x{x
x+x+x+x+x+x+x+x+x$xsxuxcxcxexsxsx+x=x+x'xDxexaxlx+xuxpxdxaxtxexdx+xsxuxcxcxexsxsxfxuxlxlxyx!x'x;x
x+x+x+x+x+x+x+x+x$xsxtxmxtx2x+x=x+x$xcxoxnxnx-x>xpxrxexpxaxrxex(x"xSxExLxExCxTx+x*x+xFxRxOxMx+xdxexaxlxsx+xWxHxExRxEx+xixdx+x=x+x?x"x)x;x
x+x+x+x+x+x+x+x+x$xsxtxmxtx2x-x>xbxixnxdx_xpxaxrxaxmx(x"xix"x,x+x$xixdx)x;x
x+x+x+x+x+x+x+x+x$xsxtxmxtx2x-x>xexxxexcxuxtxex(x)x;x
x+x+x+x+x+x+x+x+x$xdxexaxlx+x=x+x$xsxtxmxtx2x-x>xgxextx_xrxexsxuxlxtx(x)x-x>xfxextxcxhx_xaxsxsxoxcx(x)x;x
x+x+x+x+x+x+x+x+x$xsxtxmxtx2x-x>xcxlxoxsxex(x)x;x
x+x+x+x+x}x+xexlxsxex+x{x
x+x+x+x+x+x+x+x+x$xexrxrxoxrx+x=x+x'xExrxrxoxrx+xuxpxdxaxtxixnxgx+xdxexaxlx:x+x'x+x.x+x$xcxoxnxnx-x>xexrxrxoxrx;x
x+x+x+x+x}x
x+x+x+x+x$xsxtxmxtx-x>xcxlxoxsxex(x)x;x
x}x
x?x>x
x
x<x?xpxhxpx+xixfx+x(x$xsxuxcxcxexsxsx)x:x+x?x>x
x+x+x+x+x<xdxixvx+xcxlxaxsxsx=x"xaxlxexrxtx+xaxlxexrxtx-xsxuxcxcxexsxsx"x>x<xsxpxaxnx>xâxœx…x<x/xsxpxaxnx>x+x<x?x=x+xhxtxmxlxsxpxexcxixaxlxcxhxaxrxsx(x$xsxuxcxcxexsxsx)x+x?x>x<x/xdxixvx>x
x<x?xpxhxpx+xexnxdxixfx;x+x?x>x
x<x?xpxhxpx+xixfx+x(x$xexrxrxoxrx)x:x+x?x>x
x+x+x+x+x<xdxixvx+xcxlxaxsxsx=x"xaxlxexrxtx+xaxlxexrxtx-xdxaxnxgxexrx"x>x<xsxpxaxnx>xâxšx xïx¸xx<x/xsxpxaxnx>x+x<x?x=x+xhxtxmxlxsxpxexcxixaxlxcxhxaxrxsx(x$xexrxrxoxrx)x+x?x>x<x/xdxixvx>x
x<x?xpxhxpx+xexnxdxixfx;x+x?x>x
x
x<xdxixvx+xcxlxaxsxsx=x"xcxaxrxdx"x>x
x+x+x+x+x<xdxixvx+xcxlxaxsxsx=x"xcxaxrxdx-xhxexaxdxexrx"x>x
x+x+x+x+x+x+x+x+x<xhx2x>xExdxixtx+xDxexaxlx+x#x<x?x=x+x$xixdx+x?x>x<x/xhx2x>x
x+x+x+x+x+x+x+x+x<xax+xhxrxexfx=x"xdxaxsxhxbxoxaxrxdx.xpxhxpx?xpxaxgxex=xvxixexwx_xdxexaxlxsx"x+xcxlxaxsxsx=x"xbxtxnx+xbxtxnx-xoxuxtxlxixnxex+xbxtxnx-xsxmx"x>xâx†xx+xBxaxcxkx+xtxox+xDxexaxlxsx<x/xax>x
x+x+x+x+x<x/xdxixvx>x
x+x+x+x+x<xfxoxrxmx+xmxextxhxoxdx=x"xPxOxSxTx"x+xdxaxtxax-xvxaxlxixdxaxtxex>x
x+x+x+x+x+x+x+x+x<xdxixvx+xcxlxaxsxsx=x"xfxoxrxmx-xrxoxwx"x>x
x+x+x+x+x+x+x+x+x+x+x+x+x<xdxixvx+xcxlxaxsxsx=x"xfxoxrxmx-xgxrxoxuxpx"x>x
x+x+x+x+x+x+x+x+x+x+x+x+x+x+x+x+x<xlxaxbxexlx+xfxoxrx=x"xlxexaxdx_xixdx"x>xLxexaxdx<x/xlxaxbxexlx>x
x+x+x+x+x+x+x+x+x+x+x+x+x+x+x+x+x<xsxexlxexcxtx+xixdx=x"xlxexaxdx_xixdx"x+xnxaxmxex=x"xlxexaxdx_xixdx"x+xcxlxaxsxsx=x"xfxoxrxmx-xcxoxnxtxrxoxlx"x+xrxexqxuxixrxexdx>x
x+x+x+x+x+x+x+x+x+x+x+x+x+x+x+x+x+x+x+x+x<xoxpxtxixoxnx+xvxaxlxuxex=x"x"x>xSxexlxexcxtx+xax+xlxexaxdx<x/xoxpxtxixoxnx>x
x+x+x+x+x+x+x+x+x+x+x+x+x+x+x+x+x+x+x+x+x<x?xpxhxpx+xixfx+x(x$xlxexaxdxsx_xrxexsxuxlxtx)x:x+xwxhxixlxex+x(x$xlxexaxdx+x=x+x$xlxexaxdxsx_xrxexsxuxlxtx-x>xfxextxcxhx_xaxsxsxoxcx(x)x)x:x+x?x>x
x+x+x+x+x+x+x+x+x+x+x+x+x+x+x+x+x+x+x+x+x+x+x+x+x<xoxpxtxixoxnx+xvxaxlxuxex=x"x<x?x=x+x$xlxexaxdx[x'xixdx'x]x+x?x>x"x+x<x?x=x+x$xdxexaxlx[x'xlxexaxdx_xixdx'x]x+x=x=x+x$xlxexaxdx[x'xixdx'x]x+x?x+x'xsxexlxexcxtxexdx'x+x:x+x'x'x+x?x>x>x<x?x=x+xhxtxmxlxsxpxexcxixaxlxcxhxaxrxsx(x$xlxexaxdx[x'xixdx'x]x+x.x+x'x+xâx€x”x+x'x+x.x+x$xlxexaxdx[x'xnxaxmxex'x]x)x+x?x>x<x/xoxpxtxixoxnx>x
x+x+x+x+x+x+x+x+x+x+x+x+x+x+x+x+x+x+x+x+x<x?xpxhxpx+xexnxdxwxhxixlxex;x+xexnxdxixfx;x+x?x>x
x+x+x+x+x+x+x+x+x+x+x+x+x+x+x+x+x<x/xsxexlxexcxtx>x
x+x+x+x+x+x+x+x+x+x+x+x+x<x/xdxixvx>x
x+x+x+x+x+x+x+x+x+x+x+x+x<xdxixvx+xcxlxaxsxsx=x"xfxoxrxmx-xgxrxoxuxpx"x>x
x+x+x+x+x+x+x+x+x+x+x+x+x+x+x+x+x<xlxaxbxexlx+xfxoxrx=x"xdxexaxlx_xvxaxlxuxex"x>xDxexaxlx+xVxaxlxuxex<x/xlxaxbxexlx>x
x+x+x+x+x+x+x+x+x+x+x+x+x+x+x+x+x<xixnxpxuxtx+xtxyxpxex=x"xtxexxxtx"x+xixdx=x"xdxexaxlx_xvxaxlxuxex"x+xnxaxmxex=x"xdxexaxlx_xvxaxlxuxex"x+xcxlxaxsxsx=x"xfxoxrxmx-xcxoxnxtxrxoxlx"x+xvxaxlxuxex=x"x<x?x=x+xhxtxmxlxsxpxexcxixaxlxcxhxaxrxsx(x$xdxexaxlx[x'xdxexaxlx_xvxaxlxuxex'x]x)x+x?x>x"x+xrxexqxuxixrxexdx>x
x+x+x+x+x+x+x+x+x+x+x+x+x<x/xdxixvx>x
x+x+x+x+x+x+x+x+x<x/xdxixvx>x
x+x+x+x+x+x+x+x+x<xdxixvx+xcxlxaxsxsx=x"xfxoxrxmx-xrxoxwx"x>x
x+x+x+x+x+x+x+x+x+x+x+x+x<xdxixvx+xcxlxaxsxsx=x"xfxoxrxmx-xgxrxoxuxpx"x>x
x+x+x+x+x+x+x+x+x+x+x+x+x+x+x+x+x<xlxaxbxexlx+xfxoxrx=x"xexxxpxexcxtxexdx_xcxlxoxsxex"x>xExxxpxexcxtxexdx+xCxlxoxsxex+xDxaxtxex<x/xlxaxbxexlx>x
x+x+x+x+x+x+x+x+x+x+x+x+x+x+x+x+x<xixnxpxuxtx+xtxyxpxex=x"xdxaxtxex"x+xixdx=x"xexxxpxexcxtxexdx_xcxlxoxsxex"x+xnxaxmxex=x"xexxxpxexcxtxexdx_xcxlxoxsxex"x+xcxlxaxsxsx=x"xfxoxrxmx-xcxoxnxtxrxoxlx"x+xvxaxlxuxex=x"x<x?x=x+xhxtxmxlxsxpxexcxixaxlxcxhxaxrxsx(x$xdxexaxlx[x'xexxxpxexcxtxexdx_xcxlxoxsxex'x]x)x+x?x>x"x>x
x+x+x+x+x+x+x+x+x+x+x+x+x<x/xdxixvx>x
x+x+x+x+x+x+x+x+x+x+x+x+x<xdxixvx+xcxlxaxsxsx=x"xfxoxrxmx-xgxrxoxuxpx"x>x
x+x+x+x+x+x+x+x+x+x+x+x+x+x+x+x+x<xlxaxbxexlx+xfxoxrx=x"xsxtxaxtxuxsx"x>xSxtxaxtxuxsx<x/xlxaxbxexlx>x
x+x+x+x+x+x+x+x+x+x+x+x+x+x+x+x+x<xsxexlxexcxtx+xixdx=x"xsxtxaxtxuxsx"x+xnxaxmxex=x"xsxtxaxtxuxsx"x+xcxlxaxsxsx=x"xfxoxrxmx-xcxoxnxtxrxoxlx"x>x
x+x+x+x+x+x+x+x+x+x+x+x+x+x+x+x+x+x+x+x+x<x?xpxhxpx+xfxoxrxexaxcxhx+x(x[x'xOxpxexnx'x,x+x'xWxoxnx'x,x+x'xLxoxsxtx'x,x+x'xPxexnxdxixnxgx'x]x+xaxsx+x$xoxpxtx)x:x+x?x>x
x+x+x+x+x+x+x+x+x+x+x+x+x+x+x+x+x+x+x+x+x+x+x+x+x<xoxpxtxixoxnx+xvxaxlxuxex=x"x<x?x=x+x$xoxpxtx+x?x>x"x+x<x?x=x+x$xdxexaxlx[x'xsxtxaxtxuxsx'x]x+x=x=x=x+x$xoxpxtx+x?x+x'xsxexlxexcxtxexdx'x+x:x+x'x'x+x?x>x>x<x?x=x+x$xoxpxtx+x?x>x<x/xoxpxtxixoxnx>x
x+x+x+x+x+x+x+x+x+x+x+x+x+x+x+x+x+x+x+x+x<x?xpxhxpx+xexnxdxfxoxrxexaxcxhx;x+x?x>x
x+x+x+x+x+x+x+x+x+x+x+x+x+x+x+x+x<x/xsxexlxexcxtx>x
x+x+x+x+x+x+x+x+x+x+x+x+x<x/xdxixvx>x
x+x+x+x+x+x+x+x+x<x/xdxixvx>x
x+x+x+x+x+x+x+x+x<xbxuxtxtxoxnx+xtxyxpxex=x"xsxuxbxmxixtx"x+xcxlxaxsxsx=x"xbxtxnx+xbxtxnx-xpxrxixmxaxrxyx"x>xðxŸx’x¾x+xUxpxdxaxtxex+xDxexaxlx<x/xbxuxtxtxoxnx>x
x+x+x+x+x<x/xfxoxrxmx>x
x<x/xdxixvx>x
x