x<x?xpxhxpx
x$xsxuxcxcxexsxsx+x=x+x'x'x;x
x$xexrxrxoxrx+x=x+x'x'x;x
x$xlxexaxdx+x=x+xnxuxlxlx;x
x
x$xixdx+x=x+xixnxtxvxaxlx(x$x_xGxExTx[x'xixdx'x]x+x?x?x+x0x)x;x
xixfx+x(x$xixdx+x<x=x+x0x)x+x{x
x+x+x+x+xexcxhxox+x'x<xdxixvx+xcxlxaxsxsx=x"xaxlxexrxtx+xaxlxexrxtx-xdxaxnxgxexrx"x>xIxnxvxaxlxixdx+xlxexaxdx+xIxDx.x<x/xdxixvx>x'x;x
x+x+x+x+xrxextxuxrxnx;x
x}x
x
x/x/x+xFxextxcxhx+xsxaxlxexsx+xuxsxexrxsx+xfxoxrx+xdxrxoxpxdxoxwxnx
x$xsxaxlxexsx_xuxsxexrxsx_xrxexsxuxlxtx+x=x+x$xcxoxnxnx-x>xqxuxexrxyx(x"xSxExLxExCxTx+xixdx,x+xnxaxmxex+xFxRxOxMx+xsxaxlxexsx_xuxsxexrxsx+xOxRxDxExRx+xBxYx+xnxaxmxex"x)x;x
x
x/x/x+xFxextxcxhx+xexxxixsxtxixnxgx+xlxexaxdx
x$xsxtxmxtx+x=x+x$xcxoxnxnx-x>xpxrxexpxaxrxex(x"xSxExLxExCxTx+x*x+xFxRxOxMx+xlxexaxdxsx+xWxHxExRxEx+xixdx+x=x+x?x"x)x;x
x$xsxtxmxtx-x>xbxixnxdx_xpxaxrxaxmx(x"xix"x,x+x$xixdx)x;x
x$xsxtxmxtx-x>xexxxexcxuxtxex(x)x;x
x$xlxexaxdx+x=x+x$xsxtxmxtx-x>xgxextx_xrxexsxuxlxtx(x)x-x>xfxextxcxhx_xaxsxsxoxcx(x)x;x
x$xsxtxmxtx-x>xcxlxoxsxex(x)x;x
x
xixfx+x(x!x$xlxexaxdx)x+x{x
x+x+x+x+xexcxhxox+x'x<xdxixvx+xcxlxaxsxsx=x"xaxlxexrxtx+xaxlxexrxtx-xdxaxnxgxexrx"x>xLxexaxdx+xnxoxtx+xfxoxuxnxdx.x<x/xdxixvx>x'x;x
x+x+x+x+xrxextxuxrxnx;x
x}x
x
xixfx+x(x$x_xSxExRxVxExRx[x'xRxExQxUxExSxTx_xMxExTxHxOxDx'x]x+x=x=x=x+x'xPxOxSxTx'x)x+x{x
x+x+x+x+x$xnxaxmxex+x=x+xtxrxixmx(x$x_xPxOxSxTx[x'xnxaxmxex'x]x+x?x?x+x'x'x)x;x
x+x+x+x+x$xmxoxbxixlxex+x=x+xtxrxixmx(x$x_xPxOxSxTx[x'xmxoxbxixlxex'x]x+x?x?x+x'x'x)x;x
x+x+x+x+x$xexmxaxixlx+x=x+xtxrxixmx(x$x_xPxOxSxTx[x'xexmxaxixlx'x]x+x?x?x+x'x'x)x;x
x+x+x+x+x$xsxoxuxrxcxex+x=x+xtxrxixmx(x$x_xPxOxSxTx[x'xsxoxuxrxcxex'x]x+x?x?x+x'x'x)x;x
x+x+x+x+x$xsxtxaxtxuxsx+x=x+xtxrxixmx(x$x_xPxOxSxTx[x'xsxtxaxtxuxsx'x]x+x?x?x+x'x'x)x;x
x+x+x+x+x$xaxsxsxixgxnxexdx_xtxox+x=x+xtxrxixmx(x$x_xPxOxSxTx[x'xaxsxsxixgxnxexdx_xtxox'x]x+x?x?x+x'x'x)x;x
x
x+x+x+x+xixfx+x(xexmxpxtxyx(x$xnxaxmxex)x+x|x|x+xexmxpxtxyx(x$xmxoxbxixlxex)x)x+x{x
x+x+x+x+x+x+x+x+x$xexrxrxoxrx+x=x+x'xNxaxmxex+xaxnxdx+xmxoxbxixlxex+xaxrxex+xrxexqxuxixrxexdx.x'x;x
x+x+x+x+x}x+xexlxsxex+x{x
x+x+x+x+x+x+x+x+x$xsxtxmxtx+x=x+x$xcxoxnxnx-x>xpxrxexpxaxrxex(x"xUxPxDxAxTxEx+xlxexaxdxsx+xSxExTx+xnxaxmxex=x?x,x+xmxoxbxixlxex=x?x,x+xexmxaxixlx=x?x,x+xsxoxuxrxcxex=x?x,x+xsxtxaxtxuxsx=x?x,x+xaxsxsxixgxnxexdx_xtxox=x?x+xWxHxExRxEx+xixdx=x?x"x)x;x
x+x+x+x+x+x+x+x+x$xsxtxmxtx-x>xbxixnxdx_xpxaxrxaxmx(x"xsxsxsxsxsxsxix"x,x+x$xnxaxmxex,x+x$xmxoxbxixlxex,x+x$xexmxaxixlx,x+x$xsxoxuxrxcxex,x+x$xsxtxaxtxuxsx,x+x$xaxsxsxixgxnxexdx_xtxox,x+x$xixdx)x;x
x+x+x+x+x+x+x+x+xixfx+x(x$xsxtxmxtx-x>xexxxexcxuxtxex(x)x)x+x{x
x+x+x+x+x+x+x+x+x+x+x+x+x$xsxuxcxcxexsxsx+x=x+x'xLxexaxdx+xuxpxdxaxtxexdx+xsxuxcxcxexsxsxfxuxlxlxyx!x'x;x
x+x+x+x+x+x+x+x+x+x+x+x+x/x/x+xRxexfxrxexsxhx+xdxaxtxax
x+x+x+x+x+x+x+x+x+x+x+x+x$xsxtxmxtx2x+x=x+x$xcxoxnxnx-x>xpxrxexpxaxrxex(x"xSxExLxExCxTx+x*x+xFxRxOxMx+xlxexaxdxsx+xWxHxExRxEx+xixdx+x=x+x?x"x)x;x
x+x+x+x+x+x+x+x+x+x+x+x+x$xsxtxmxtx2x-x>xbxixnxdx_xpxaxrxaxmx(x"xix"x,x+x$xixdx)x;x
x+x+x+x+x+x+x+x+x+x+x+x+x$xsxtxmxtx2x-x>xexxxexcxuxtxex(x)x;x
x+x+x+x+x+x+x+x+x+x+x+x+x$xlxexaxdx+x=x+x$xsxtxmxtx2x-x>xgxextx_xrxexsxuxlxtx(x)x-x>xfxextxcxhx_xaxsxsxoxcx(x)x;x
x+x+x+x+x+x+x+x+x+x+x+x+x$xsxtxmxtx2x-x>xcxlxoxsxex(x)x;x
x+x+x+x+x+x+x+x+x}x+xexlxsxex+x{x
x+x+x+x+x+x+x+x+x+x+x+x+x$xexrxrxoxrx+x=x+x'xExrxrxoxrx+xuxpxdxaxtxixnxgx+xlxexaxdx:x+x'x+x.x+x$xcxoxnxnx-x>xexrxrxoxrx;x
x+x+x+x+x+x+x+x+x}x
x+x+x+x+x+x+x+x+x$xsxtxmxtx-x>xcxlxoxsxex(x)x;x
x+x+x+x+x}x
x}x
x?x>x
x
x<x?xpxhxpx+xixfx+x(x$xsxuxcxcxexsxsx)x:x+x?x>x
x+x+x+x+x<xdxixvx+xcxlxaxsxsx=x"xaxlxexrxtx+xaxlxexrxtx-xsxuxcxcxexsxsx"x>x<xsxpxaxnx>xâxœx…x<x/xsxpxaxnx>x+x<x?x=x+xhxtxmxlxsxpxexcxixaxlxcxhxaxrxsx(x$xsxuxcxcxexsxsx)x+x?x>x<x/xdxixvx>x
x<x?xpxhxpx+xexnxdxixfx;x+x?x>x
x<x?xpxhxpx+xixfx+x(x$xexrxrxoxrx)x:x+x?x>x
x+x+x+x+x<xdxixvx+xcxlxaxsxsx=x"xaxlxexrxtx+xaxlxexrxtx-xdxaxnxgxexrx"x>x<xsxpxaxnx>xâxšx xïx¸xx<x/xsxpxaxnx>x+x<x?x=x+xhxtxmxlxsxpxexcxixaxlxcxhxaxrxsx(x$xexrxrxoxrx)x+x?x>x<x/xdxixvx>x
x<x?xpxhxpx+xexnxdxixfx;x+x?x>x
x
x<xdxixvx+xcxlxaxsxsx=x"xcxaxrxdx"x>x
x+x+x+x+x<xdxixvx+xcxlxaxsxsx=x"xcxaxrxdx-xhxexaxdxexrx"x>x
x+x+x+x+x+x+x+x+x<xhx2x>xExdxixtx+xLxexaxdx+x#x<x?x=x+x$xixdx+x?x>x<x/xhx2x>x
x+x+x+x+x+x+x+x+x<xax+xhxrxexfx=x"xdxaxsxhxbxoxaxrxdx.xpxhxpx?xpxaxgxex=xvxixexwx_xlxexaxdxsx"x+xcxlxaxsxsx=x"xbxtxnx+xbxtxnx-xoxuxtxlxixnxex+xbxtxnx-xsxmx"x>xâx†xx+xBxaxcxkx+xtxox+xLxexaxdxsx<x/xax>x
x+x+x+x+x<x/xdxixvx>x
x+x+x+x+x<xfxoxrxmx+xmxextxhxoxdx=x"xPxOxSxTx"x+xdxaxtxax-xvxaxlxixdxaxtxex>x
x+x+x+x+x+x+x+x+x<xdxixvx+xcxlxaxsxsx=x"xfxoxrxmx-xrxoxwx"x>x
x+x+x+x+x+x+x+x+x+x+x+x+x<xdxixvx+xcxlxaxsxsx=x"xfxoxrxmx-xgxrxoxuxpx"x>x
x+x+x+x+x+x+x+x+x+x+x+x+x+x+x+x+x<xlxaxbxexlx+xfxoxrx=x"xnxaxmxex"x>xNxaxmxex+x<xsxpxaxnx+xcxlxaxsxsx=x"xrxexqxuxixrxexdx"x>x*x<x/xsxpxaxnx>x<x/xlxaxbxexlx>x
x+x+x+x+x+x+x+x+x+x+x+x+x+x+x+x+x<xixnxpxuxtx+xtxyxpxex=x"xtxexxxtx"x+xixdx=x"xnxaxmxex"x+xnxaxmxex=x"xnxaxmxex"x+xcxlxaxsxsx=x"xfxoxrxmx-xcxoxnxtxrxoxlx"x+xvxaxlxuxex=x"x<x?x=x+xhxtxmxlxsxpxexcxixaxlxcxhxaxrxsx(x$xlxexaxdx[x'xnxaxmxex'x]x)x+x?x>x"x+xrxexqxuxixrxexdx>x
x+x+x+x+x+x+x+x+x+x+x+x+x<x/xdxixvx>x
x+x+x+x+x+x+x+x+x+x+x+x+x<xdxixvx+xcxlxaxsxsx=x"xfxoxrxmx-xgxrxoxuxpx"x>x
x+x+x+x+x+x+x+x+x+x+x+x+x+x+x+x+x<xlxaxbxexlx+xfxoxrx=x"xmxoxbxixlxex"x>xMxoxbxixlxex+x<xsxpxaxnx+xcxlxaxsxsx=x"xrxexqxuxixrxexdx"x>x*x<x/xsxpxaxnx>x<x/xlxaxbxexlx>x
x+x+x+x+x+x+x+x+x+x+x+x+x+x+x+x+x<xixnxpxuxtx+xtxyxpxex=x"xtxexxxtx"x+xixdx=x"xmxoxbxixlxex"x+xnxaxmxex=x"xmxoxbxixlxex"x+xcxlxaxsxsx=x"xfxoxrxmx-xcxoxnxtxrxoxlx"x+xvxaxlxuxex=x"x<x?x=x+xhxtxmxlxsxpxexcxixaxlxcxhxaxrxsx(x$xlxexaxdx[x'xmxoxbxixlxex'x]x)x+x?x>x"x+xrxexqxuxixrxexdx>x
x+x+x+x+x+x+x+x+x+x+x+x+x<x/xdxixvx>x
x+x+x+x+x+x+x+x+x<x/xdxixvx>x
x+x+x+x+x+x+x+x+x<xdxixvx+xcxlxaxsxsx=x"xfxoxrxmx-xrxoxwx"x>x
x+x+x+x+x+x+x+x+x+x+x+x+x<xdxixvx+xcxlxaxsxsx=x"xfxoxrxmx-xgxrxoxuxpx"x>x
x+x+x+x+x+x+x+x+x+x+x+x+x+x+x+x+x<xlxaxbxexlx+xfxoxrx=x"xexmxaxixlx"x>xExmxaxixlx<x/xlxaxbxexlx>x
x+x+x+x+x+x+x+x+x+x+x+x+x+x+x+x+x<xixnxpxuxtx+xtxyxpxex=x"xexmxaxixlx"x+xixdx=x"xexmxaxixlx"x+xnxaxmxex=x"xexmxaxixlx"x+xcxlxaxsxsx=x"xfxoxrxmx-xcxoxnxtxrxoxlx"x+xvxaxlxuxex=x"x<x?x=x+xhxtxmxlxsxpxexcxixaxlxcxhxaxrxsx(x$xlxexaxdx[x'xexmxaxixlx'x]x)x+x?x>x"x>x
x+x+x+x+x+x+x+x+x+x+x+x+x<x/xdxixvx>x
x+x+x+x+x+x+x+x+x+x+x+x+x<xdxixvx+xcxlxaxsxsx=x"xfxoxrxmx-xgxrxoxuxpx"x>x
x+x+x+x+x+x+x+x+x+x+x+x+x+x+x+x+x<xlxaxbxexlx+xfxoxrx=x"xsxoxuxrxcxex"x>xSxoxuxrxcxex<x/xlxaxbxexlx>x
x+x+x+x+x+x+x+x+x+x+x+x+x+x+x+x+x<xsxexlxexcxtx+xixdx=x"xsxoxuxrxcxex"x+xnxaxmxex=x"xsxoxuxrxcxex"x+xcxlxaxsxsx=x"xfxoxrxmx-xcxoxnxtxrxoxlx"x>x
x+x+x+x+x+x+x+x+x+x+x+x+x+x+x+x+x+x+x+x+x<x?xpxhxpx+xfxoxrxexaxcxhx+x(x[x'x'x,x+x'xWxexbxsxixtxex'x,x+x'xRxexfxexrxrxaxlx'x,x+x'xSxoxcxixaxlx+xMxexdxixax'x,x+x'xCxoxlxdx+xCxaxlxlx'x,x+x'xExmxaxixlx+xCxaxmxpxaxixgxnx'x,x+x'xOxtxhxexrx'x]x+xaxsx+x$xoxpxtx)x:x+x?x>x
x+x+x+x+x+x+x+x+x+x+x+x+x+x+x+x+x+x+x+x+x+x+x+x+x<xoxpxtxixoxnx+xvxaxlxuxex=x"x<x?x=x+x$xoxpxtx+x?x>x"x+x<x?x=x+x$xlxexaxdx[x'xsxoxuxrxcxex'x]x+x=x=x=x+x$xoxpxtx+x?x+x'xsxexlxexcxtxexdx'x+x:x+x'x'x+x?x>x>x<x?x=x+x$xoxpxtx+x?x:x+x'xSxexlxexcxtx+xsxoxuxrxcxex'x+x?x>x<x/xoxpxtxixoxnx>x
x+x+x+x+x+x+x+x+x+x+x+x+x+x+x+x+x+x+x+x+x<x?xpxhxpx+xexnxdxfxoxrxexaxcxhx;x+x?x>x
x+x+x+x+x+x+x+x+x+x+x+x+x+x+x+x+x<x/xsxexlxexcxtx>x
x+x+x+x+x+x+x+x+x+x+x+x+x<x/xdxixvx>x
x+x+x+x+x+x+x+x+x<x/xdxixvx>x
x+x+x+x+x+x+x+x+x<xdxixvx+xcxlxaxsxsx=x"xfxoxrxmx-xrxoxwx"x>x
x+x+x+x+x+x+x+x+x+x+x+x+x<xdxixvx+xcxlxaxsxsx=x"xfxoxrxmx-xgxrxoxuxpx"x>x
x+x+x+x+x+x+x+x+x+x+x+x+x+x+x+x+x<xlxaxbxexlx+xfxoxrx=x"xsxtxaxtxuxsx"x>xSxtxaxtxuxsx<x/xlxaxbxexlx>x
x+x+x+x+x+x+x+x+x+x+x+x+x+x+x+x+x<xsxexlxexcxtx+xixdx=x"xsxtxaxtxuxsx"x+xnxaxmxex=x"xsxtxaxtxuxsx"x+xcxlxaxsxsx=x"xfxoxrxmx-xcxoxnxtxrxoxlx"x>x
x+x+x+x+x+x+x+x+x+x+x+x+x+x+x+x+x+x+x+x+x<x?xpxhxpx+xfxoxrxexaxcxhx+x(x[x'xNxexwx'x,x+x'xCxoxnxtxaxcxtxexdx'x,x+x'xQxuxaxlxixfxixexdx'x,x+x'xCxoxnxvxexrxtxexdx'x,x+x'xLxoxsxtx'x]x+xaxsx+x$xoxpxtx)x:x+x?x>x
x+x+x+x+x+x+x+x+x+x+x+x+x+x+x+x+x+x+x+x+x+x+x+x+x<xoxpxtxixoxnx+xvxaxlxuxex=x"x<x?x=x+x$xoxpxtx+x?x>x"x+x<x?x=x+x$xlxexaxdx[x'xsxtxaxtxuxsx'x]x+x=x=x=x+x$xoxpxtx+x?x+x'xsxexlxexcxtxexdx'x+x:x+x'x'x+x?x>x>x<x?x=x+x$xoxpxtx+x?x>x<x/xoxpxtxixoxnx>x
x+x+x+x+x+x+x+x+x+x+x+x+x+x+x+x+x+x+x+x+x<x?xpxhxpx+xexnxdxfxoxrxexaxcxhx;x+x?x>x
x+x+x+x+x+x+x+x+x+x+x+x+x+x+x+x+x<x/xsxexlxexcxtx>x
x+x+x+x+x+x+x+x+x+x+x+x+x<x/xdxixvx>x
x+x+x+x+x+x+x+x+x+x+x+x+x<xdxixvx+xcxlxaxsxsx=x"xfxoxrxmx-xgxrxoxuxpx"x>x
x+x+x+x+x+x+x+x+x+x+x+x+x+x+x+x+x<xlxaxbxexlx+xfxoxrx=x"xaxsxsxixgxnxexdx_xtxox"x>xAxsxsxixgxnxexdx+xTxox<x/xlxaxbxexlx>x
x+x+x+x+x+x+x+x+x+x+x+x+x+x+x+x+x<xsxexlxexcxtx+xixdx=x"xaxsxsxixgxnxexdx_xtxox"x+xnxaxmxex=x"xaxsxsxixgxnxexdx_xtxox"x+xcxlxaxsxsx=x"xfxoxrxmx-xcxoxnxtxrxoxlx"x>x
x+x+x+x+x+x+x+x+x+x+x+x+x+x+x+x+x+x+x+x+x<xoxpxtxixoxnx+xvxaxlxuxex=x"x"x>xUxnxaxsxsxixgxnxexdx<x/xoxpxtxixoxnx>x
x+x+x+x+x+x+x+x+x+x+x+x+x+x+x+x+x+x+x+x+x<x?xpxhxpx+xixfx+x(x$xsxaxlxexsx_xuxsxexrxsx_xrxexsxuxlxtx)x:x+xwxhxixlxex+x(x$xuxsxexrx+x=x+x$xsxaxlxexsx_xuxsxexrxsx_xrxexsxuxlxtx-x>xfxextxcxhx_xaxsxsxoxcx(x)x)x:x+x?x>x
x+x+x+x+x+x+x+x+x+x+x+x+x+x+x+x+x+x+x+x+x+x+x+x+x<xoxpxtxixoxnx+xvxaxlxuxex=x"x<x?x=x+xhxtxmxlxsxpxexcxixaxlxcxhxaxrxsx(x$xuxsxexrx[x'xnxaxmxex'x]x)x+x?x>x"x+x<x?x=x+x$xlxexaxdx[x'xaxsxsxixgxnxexdx_xtxox'x]x+x=x=x=x+x$xuxsxexrx[x'xnxaxmxex'x]x+x?x+x'xsxexlxexcxtxexdx'x+x:x+x'x'x+x?x>x>x<x?x=x+xhxtxmxlxsxpxexcxixaxlxcxhxaxrxsx(x$xuxsxexrx[x'xnxaxmxex'x]x)x+x?x>x<x/xoxpxtxixoxnx>x
x+x+x+x+x+x+x+x+x+x+x+x+x+x+x+x+x+x+x+x+x<x?xpxhxpx+xexnxdxwxhxixlxex;x+xexnxdxixfx;x+x?x>x
x+x+x+x+x+x+x+x+x+x+x+x+x+x+x+x+x<x/xsxexlxexcxtx>x
x+x+x+x+x+x+x+x+x+x+x+x+x<x/xdxixvx>x
x+x+x+x+x+x+x+x+x<x/xdxixvx>x
x+x+x+x+x+x+x+x+x<xbxuxtxtxoxnx+xtxyxpxex=x"xsxuxbxmxixtx"x+xcxlxaxsxsx=x"xbxtxnx+xbxtxnx-xpxrxixmxaxrxyx"x>xðxŸx’x¾x+xUxpxdxaxtxex+xLxexaxdx<x/xbxuxtxtxoxnx>x
x+x+x+x+x<x/xfxoxrxmx>x
x<x/xdxixvx>x
x